// Mocks generated by Mockito 5.4.4 from annotations
// in sia_app/test/bloc/home/home_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:sia_app/core/failures.dart' as _i5;
import 'package:sia_app/data/models/user_detail.dart' as _i6;
import 'package:sia_app/data/repository/user_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.UserDetail>> getDetail() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetail,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.UserDetail>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, _i6.UserDetail>>(
          this,
          Invocation.method(
            #getDetail,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Either<_i5.Failure, _i6.UserDetail>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i6.UserDetail>>(
          this,
          Invocation.method(
            #getDetail,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.UserDetail>>);
}
