// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFPKgGWdWCTrElFMurgByHzmCa7qiWq0o',
    appId: '1:1016311512981:web:3b0bd5b287ea53ff5a809c',
    messagingSenderId: '1016311512981',
    projectId: 'sia-app-f2f94',
    authDomain: 'sia-app-f2f94.firebaseapp.com',
    storageBucket: 'sia-app-f2f94.appspot.com',
    measurementId: 'G-4FJ6CD49DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrtI0qJpMiy8iWBfvDY3VHt8yt6IFQcZ8',
    appId: '1:1016311512981:android:4f07a811e43ddf755a809c',
    messagingSenderId: '1016311512981',
    projectId: 'sia-app-f2f94',
    storageBucket: 'sia-app-f2f94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtifNif6bEOWk4frw2misvPNBLnNNTurs',
    appId: '1:1016311512981:ios:48fa8c6c65211c4c5a809c',
    messagingSenderId: '1016311512981',
    projectId: 'sia-app-f2f94',
    storageBucket: 'sia-app-f2f94.appspot.com',
    iosBundleId: 'com.example.siaApp',
  );
}
